name: MAIN Flow

on:
  push:
    branches:
      - main

jobs:
  build_upload_to_s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!