name: MAIN Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello_job_main_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!